### PR TITLE
442 own courses revamp

### PR DESCRIPTION
**Pull request by Jickelsen**

### CODE REVIEW

**Comment by MartinMarcusson** [comment]
Långa namn på organisationer blir avkapade, se bild.

image

**Comment by MartinMarcusson** [comment]
Text that can not be clicked has hover-effect, this feels misleading. E.g. "IMPORTERAD FRÅN SUSA NAVET" and dates in column "Redigeringsdatum".

**Comment by Jickelsen** [comment]
Styling has been noninteractive elements no longer have a hover effect, text cutout should be fixed and the screen has had numerous styling fixes
Screenshot 2023-02-28 at 20 39 32

**Review by MartinMarcusson — APPROVED** [review]

**Comment by MartinMarcusson** [comment]
With this update it is no longer possible to view courses that do not have an edge to an organization. This is realistically only a problem for the admin user.

**Pull request merged**
